# Generated by Django 2.2.16 on 2022-07-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='amount',
            field=models.FloatField(max_length=7),
        ),
        migrations.AlterField(
            model_name='currency',
            name='value',
            field=models.FloatField(max_length=7),
        ),
    ]
